FROM public.ecr.aws/docker/library/node:20-slim
RUN npm install -g npm@latest --loglevel=error

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --loglevel=error

COPY client/package*.json ./client/
RUN cd client && npm install --loglevel=error

COPY . .

ENV VITE_API_URL=http://localhost:8080
RUN cd client && npm run build

EXPOSE 8080

CMD [ "npm", "start" ]
